FROM mongo:3.5.11

# Create app directory
#WORKDIR /usr/src/app

# Install app dependencies
#COPY package.json .
# For npm@5 or later, copy package-lock.json as well
# COPY package.json package-lock.json .

#RUN npm install

# Bundle app source
#COPY . .

#EXPOSE 27017
#CMD [ "npm", "start" ]